innocenzi/laravel-vite

- src/Vite.php
- src/ViteServiceProvider.php
- src/helpers.php
- tests/Unit/BladeDirectivesTest.php
- tests/Unit/ViteTest.php
This replaces the original `@vite` directive behavior.
Instead, `@client` must be used.
Now, you only need `@vite` in your Blade file to include every automatic entrypoint. 
If you have different entry points configured in `vite.config.ts`, they'll need to be included manually with `@vite('relative/path/to/script.ts')`.
Closes #5.
> refactor!: support importing every entrypoints at once

- npm/package.json
- npm/src/index.ts
- npm/yarn.lock
- src/ManifestEntry.php
- src/Vite.php
- tests/Unit/ViteTest.php
This creates support for the `ASSET_URL` environment variable, just like Laravel's `asset` helper. This updates Vite's `base` property. In development, this is ignored.
Closes #6.
> feat!: support `ASSET_URL` environment variable

- composer.json
- composer.lock
- config/vite.php
- src/Exceptions/ManifestNotFound.php
- src/Vite.php
- tests/Unit/DevelopmentServerTest.php
- tests/Unit/ViteTest.php
This PR implements falling back to the manifest if the environment is `local` but the development server is not running. 
It works by pinging the `dev_url` URL at `/@vite/client`. This ping is not performed while in another environment than `local`.
Closes #24
> feat: fallback to manifest if server is not running

- src/Exceptions/NoSuchEntrypointException.php
- src/Manifest.php
- tests/Unit/ViteTest.php
- tests/Unit/manifests/entry.json
This fixes an error that occured if you used the convenience "entrypoint by name instead of path" feature in production.
> fix: support entrypoints by name in production

- npm/package.json
- npm/src/index.ts
- npm/yarn.lock
- src/Commands/ExportConfigurationCommand.php
- src/Vite.php
- tests/Features/ExportConfigurationCommandTest.php
This PR fixes the fact that the production build did not take into account the filter in the configuration.
> fix: properly filter entrypoints for build-time

- docs/guide/usage.md
- src/Vite.php
- src/ViteServiceProvider.php
- src/helpers.php
- tests/Unit/BladeDirectivesTest.php
This PR adds support for injecting React's refresh runtime when using the `@react` directive. This directive must be positionned before the other ones. 
A new directive was needed because there was no way of detecting the use of React from PHP.
Closes #32
> feat: support react refresh runtime

- config/vite.php
- docs/guide/configuration.md
- docs/guide/production.md
- docs/guide/usage.md
- npm/package.json
- npm/src/index.ts
- src/Vite.php
- src/helpers.php
- tests/Unit/DevelopmentServerTest.php
- tests/Unit/ViteTest.php
This PR adds a `vite_asset` helper which generates a proper URL for handling assets in Blade. 
However, assets in CSS or other Vite-handled files (such as Vue SFCs) will not properly be handled because Vite doesn't allow it yet. 
Related: https://github.com/vitejs/vite/issues/2196
> feat: add `vite_asset` helper

- docs/guide/configuration.md
Clicking on the link to the `@vite` directive in the configuration page takes me to a 404. This fix points the link to the correct location.
> docs: fix broken link to @vite directive

- src/Commands/GenerateAliasesCommand.php
- tests/Features/GenerateAliasesCommandTest.php
`baseUrl` must always be set when `paths` is set (https://www.typescriptlang.org/tsconfig#paths).
> fix: add `baseUrl` to `tsconfig.json`

- npm/src/index.ts
In certain build environments you do php related build steps separate, and such
you might not have the ability to run php commands and node commands in the same build step.
We encountered this as we run the composer step in separate containers from node build step. This would let us run vite:config in a previous step then use that config later when we build javascript/css assets.
> feat: add artisan parameter to `defineConfig`

- src/Vite.php
Currently the URL for `react-refresh` is hardcoded so it fails whenever you change the `dev_url` to anything else than the default value (`http://localhost:3000`). This PR fixes that.
> fix: take dev_url config into account for react-refresh url

- src/ViteServiceProvider.php
Sorry, but I faced no problems on running a Laravel project with `ViteServiceProvider::bootingPackage()` neither with `ViteServiceProvider::registeringPackage()` (as stated in issue #108), but I still pushed the fix to ensure compatibility with `Facade\Ignition\IgnitionServiceProvider::registerViewEngines()`.
If viable, I would like to ask @callmez if they could test my fix on their project by temporary referencing on my fork branch.
I keep staying in total disposition on helping with this PR.
> refactor: use `registeringPackage` instead of `bootingPackage` with `afterResolving`

- npm/src/index.ts
Fixes #136. I tried a couple different things and this seemed like the cleanest—adding another method signature would have required both a `typeof ... === 'undefined'`, which is ugly, and also reassigning `path` and `domain` to new variables. This way the existing method signature doesn't actually change (I think?) and it's still quite readable.
[TypeScript playground.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCwiApgE2FOBfOAMyjTgHIIBnMgKBvQA9JY4BjAGwENLK4A1YDHQBhCADtCwAOYBXKJxjBxiGnDhgZAI3bBWcAO6DkfTu3Qxh6WMEmsF6SgAoIYReMoB+AFyI4mNJzAYt5wlDBQQVIA3OoKyCFhEWJS+ACUPjDIwLwINACQrO7wqBhwALwoaFg4jqmqanBm8GBx5XAubmKeAHQtmXAeHuQA9N2FEtLDAG6m5sOW1rb2lMO0DY3mfgFBbR1KXR7d-iCBYgNDYCSsDpTd6GJT3QCCAAovAPoAqgBKADKHUHQYC410cwwAesgYDAwJ4vAAdYaI4YAGnIZFSajoeTyNjgjgAhMdTpjcjiCu4IGZuvpOFAxI4y …
> fix: allow passing no arguments to `.withValetCertificates()`

- .php-cs-fixer.php
- src/Exceptions/ManifestNotFound.php
- src/Exceptions/NoSuchEntrypointException.php
- src/Exceptions/ViteException.php
- tests/Unit/DevelopmentServerTest.php
This PR adds Ignition solutions to the two exceptions that can be thrown by Laravel Vite.
> feat: add Ignition solutions to exceptions

- npm/src/index.ts
- npm/src/manifest-plugin.ts
- src/ManifestEntry.php
Fixes #153
You'll have to double check my work here - I couldn't run stuff locally.
This PR adds a manifest patching plugin, see #153. The way this plugin works is taken from Vite Ruby. This fixes support for CSS entrypoints, as well as other entrypoints, although non-JS/CSS entrypoints aren't handled by the `ManifestEntry` class, although that could be added later.
> feat: support non-script entrypoints via custom manifest

- docs/guide/configuration.md
- npm/package.json
- npm/src/index.ts
- npm/yarn.lock
With this PR, commands defined in `vite.commands` can accept arguments. For this, an array need to be used instead of a string:
```php
'commands' => [
['ziggy:generate', 'resources/ziggy-generated-routes.js'],
'vite:aliases',
'typescript:generate',
'i18n:generate',
],
```
> feat: allow for command arguments

- composer.json
- composer.lock
Laravel Vite works just fine with Guzzle 6. I'd like it to be allowed as my company is stuck with Guzzle 6 because of some other unmaintaned library.
> feat: support guzzle 6

- src/ManifestEntry.php
- src/Vite.php
- tests/Unit/ViteTest.php
This PR adds support for hooking into the logic to create style and script tags. This is useful for adding properties such as `crossorigin` or `async`/`defer` for instance.
```php
Vite::generateTagsUsing(function (string $url, string $type) {
if ($type === ManifestEntry::SCRIPT_TAG) {
return sprintf('<script type="module" src="%s" crossorigin></script>', $url);
}
return sprintf('<link rel="stylesheet" href="%s" crossorigin />', $url);
});
```
> feat: generate tags using custom logic

- src/Vite.php
- tests/Unit/ViteTest.php
The manifest should only be returned in production, so having to check if the enviroment is local falls short for when the enviroment is staging or testing. Wich would make more sense
Also see here: https://github.com/innocenzi/laravel-vite/pull/126#issuecomment-1000381350
> feat!: do not use manifest in dev or test environments

- src/Vite.php
Appreciate your work on this project, using it in numerous Laravel projects myself.
However, I've found myself running a local fork of the project which contains the changes in this PR as I had noticed, at least on the machines I develop with (Windows) there appears to be an issue with the load times when building the Blade template / HTML. On average the load time is around 6~ seconds but in some cases has taken well over 10 seconds for the initial page load.
With regards to the changes - 
I noticed an unused variable existed that looked like the intention was to cache the result of the 'isDevelopmentServerRunning' result, so I've gone and implemented this which reduces the 6-10 second load times I was experiencing down to 2~ seconds, as each load calls the 'isDevelopmentServerRunning' …
> fix: improve first load time

- src/Vite.php
As mentioned in https://github.com/innocenzi/laravel-vite/discussions/180.
This makes CSS entrypoints output as `link` tags in dev mode instead of `script` tags, preventing the CSS load delay and FOUC.
> fix: render css entrypoints as link tags in development

- src/Manifest.php
When in development mode you can specify entrypoint paths with or without a leading slash, as `Vite::getEntries()` trims the slash.
```blade
// Both of these work
{{ vite_entry('/resources/scripts/app.js') }}
{{ vite_entry('resources/scripts/app.js') }}
```
However, when using the mainfest adding a leading slash fails with `Entry '/resources/scripts/app.js' does not exist in the manifest`.
This fixes that by trimming the slash before lookup.
> fix: trim leading slash when fetching entry from manifest

- src/Vite.php
Trim leading slash from paths passed to `vite_asset`.
Currently:
```php
vite_asset('test.svg'); // http://localhost:3000/test.svg
vite_asset('/test.svg'); // http://localhost:3000//test.svg
```
With change:
```php
vite_asset('test.svg'); // http://localhost:3000/test.svg
vite_asset('/test.svg'); // http://localhost:3000/test.svg
```
I'm not sure the double slash actually matters (the paths still work), but it looks tidier and Laravel's `asset` helper does the same thing.
> fix: trim leading slash from `vite_asset` path

- docs/src/guide/introduction.md
Node version 16.15.1 gives "contexts.at is not a function" error
> docs: update minimum Node version

- src/Configuration.php
- src/Vite.php
- tests/Features/ManifestTest.php
This PR introduces a way of customizing the logic to find the path to a manifest file.
```php
Vite::findManifestPathWith(function (Configuration $configuration) {
// Custom manifest path generation logic
$buildPath = $configuration->getConfig('build_path');
return base_path($buildPath . '/public_html/manifest.json'); // adapt for your needs
});
```
Closes https://github.com/innocenzi/laravel-vite/issues/296
> feat: support generating custom manifest paths

- docs/src/guide/extra-topics/inertia.md
Changed "Components" to "Layouts"
> docs: fix typo

- docs/src/guide/quick-start.md
The docs currently say "You do need to install the CSS pre-processors you are using, though". However, the page linked to [clearly states](https://vitejs.dev/guide/features.html#css) that the base package for a CSS pre-processor must be installed if not using postcss:
> There is no need to install Vite-specific plugins for them, ***but the corresponding pre-processor itself must be installed***
> docs: update statement about CSS pre-processors

- src/Configuration.php
When developing via a proxy on a different machine the `dev_server.url` (usually something with localhost) is not the URL the client needs. This small change allows users to define `dev_server.client_url` (and if not defined falls back to `dev_server.url`) to overcome this challenge.
> feat: allow users to define client dev server url

- src/Commands/ExportConfigurationCommand.php
- src/Exceptions/NoSuchConfigurationException.php
- src/Exceptions/NoSuchEntrypointException.php
- tests/Pest.php
PHP8.2 has deprecated 1 method of string interpolation, and gives the following warning (example):
```
Using ${var} in strings is deprecated, use {$var} instead in /var/www/cmrhk/vendor/innocenzi/laravel-vite/src/Commands/ExportConfigurationCommand.php on line 27
```
More info on the RFC: https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation
Several usages of this deprecated method is found in this repo and is therefore changed.
> fix(laravel): update string interpolation
